/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3tertcnpdzgbhauqh2mjlmmygq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zlz23dh7uzbrrlnjttnvsx5icq",
    "aws_cognito_identity_pool_id": "us-east-1:90bb953a-8fb7-4df7-a726-e45062161daa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZJ7Vas0Qp",
    "aws_user_pools_web_client_id": "210j4qqa1rj7drv0ml64r8gsve",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
